<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <AssemblyName>PostQuantum.Jwt.WebApiDemo</AssemblyName>
    <RootNamespace>PostQuantum.Jwt.WebApiDemo</RootNamespace>
    <UserSecretsId>postquantum-jwt-webapidemo</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PostQuantum.Jwt\PostQuantum.Jwt.csproj" />
    <ProjectReference Include="..\..\src\PostQuantum.Jwt.AspNetCore\PostQuantum.Jwt.AspNetCore.csproj" />
  </ItemGroup>

</Project>
